### ISSUE TITLE
SEGF

### ISSUE THREAD

**Issue by vbrovenk** [olehsamoilenko/Piscine-CPP#1]
You have segfault in Day04 in ex03

**Comment by Salaaav** [comment]
You are noob

**Comment by olehsamoilenko** [comment]
Found. Creating a not-learned materia makes segfault.

**Comment by Salaaav** [comment]
Oleg take me with you to Odessa

**Comment by olehsamoilenko** [comment]
How will we fix it?

**Comment by vbrovenk** [comment]
IGRA GAVNO
